apiVersion: v1
kind: ConfigMap
metadata:
  name: issuer-node-api-configmap
  labels:
    app: issuer-node
data:
  # Public API Server API or Ingress Entry Point
  ISSUER_SERVER_URL: http://issuer-node-api.info
  ISSUER_SERVER_PORT: "3001"
  ISSUER_NATIVE_PROOF_GENERATION_ENABLED: "true"
  ISSUER_PUBLISH_KEY_PATH: pbkey
  ISSUER_ONCHAIN_PUBLISH_STATE_FREQUENCY: 1m
  ISSUER_ONCHAIN_CHECK_STATUS_FREQUENCY: 1m
  ISSUER_LOG_LEVEL: "-4"
  ISSUER_LOG_MODE: "2"
  ISSUER_API_AUTH_USER: user
  ISSUER_API_AUTH_PASSWORD: password
  ISSUER_KEY_STORE_PLUGIN_IDEN3_MOUNT_PATH: iden3
  ISSUER_REVERSE_HASH_SERVICE_ENABLED: "false"

  # Setup the RPC connection to the Ethereum node
  ISSUER_ETHEREUM_URL: https://polygon-mumbai.g.alchemy.com/v2/xaP2_t9EUM2VYDgCgMI0k9KqDyJPvZ89

  # Use this for mumbai:
  ISSUER_ETHEREUM_CONTRACT_ADDRESS: "0x134B1BE34911E39A8397ec6289782989729807a4"
  ISSUER_ETHEREUM_RESOLVER_PREFIX: polygon:mumbai

  # Use this for mainnet:
  #ISSUER_ETHEREUM_CONTRACT_ADDRESS=0x624ce98D2d27b20b8f8d521723Df8fC4db71D79D
  #ISSUER_ETHEREUM_RESOLVER_PREFIX=polygon:main

  ISSUER_ETHEREUM_DEFAULT_GAS_LIMIT: "600000"
  ISSUER_ETHEREUM_CONFIRMATION_TIME_OUT: 10s
  ISSUER_ETHEREUM_CONFIRMATION_BLOCK_COUNT: "10"
  ISSUER_ETHEREUM_RECEIPT_TIMEOUT: 600s
  ISSUER_ETHEREUM_MIN_GAS_PRICE: "0"
  ISSUER_ETHEREUM_MAX_GAS_PRICE: "1000000"
  ISSUER_ETHEREUM_RPC_RESPONSE_TIMEOUT: 5s
  ISSUER_ETHEREUM_WAIT_RECEIPT_CYCLE_TIME: 30s
  ISSUER_ETHEREUM_WAIT_BLOCK_CYCLE_TIME: 30s
  ISSUER_PROVER_SERVER_URL: http://localhost:8002
  ISSUER_PROVER_TIMEOUT: 600s
  ISSUER_CIRCUIT_PATH: "./pkg/credentials/circuits"
  ISSUER_REDIS_URL: redis://@issuer-node-redis-svc:6379/1

  ISSUER_DB_NAME: platformid
  ISSUER_DB_PORT: "5432"
  ISSUER_DB_USER: polygonid
  ISSUER_DB_PASSWORD: strongpasswordapp
  ISSUER_KEY_STORE_PORT: "8200"
  ISSUER_VAULT_USERPASS_AUTH_ENABLED: "true"
