apiVersion: v1
kind: ConfigMap
metadata:
  name: issuer-node-postgres-configmap
  labels:
    app: issuer-node
data:
  POSTGRES_DB: platformid
  POSTGRES_USER: polygonid
  POSTGRES_PASSWORD: strongpasswordapp

  init.sql: |
    CREATE DATABASE platformid;
    CREATE USER polygonid WITH ENCRYPTED PASSWORD 'strongpasswordapp';
    ALTER USER polygonid SUPERUSER;