polygon:
  # main:
  #   contractAddress: 0x624ce98D2d27b20b8f8d521723Df8fC4db71D79D
  #   networkURL: https://polygon-mainnet.g.alchemy.com/v2/X2
  #   defaultGasLimit: 600000
  #   confirmationTimeout: 10s
  #   confirmationBlockCount: 5
  #   receiptTimeout: 600s
  #   minGasPrice: 0
  #   maxGasPrice: 1000000
  #   rpcResponseTimeout: 5s
  #   waitReceiptCycleTime: 30s
  #   waitBlockCycleTime: 30s
  #   gasLess: false
  #   rhsSettings:
  #     mode: None
  #     contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
  #     rhsUrl: https://rhs-staging.polygonid.me
  #     chainID: 137
  #     publishingKey: pbkey

  amoy:
    contractAddress: 0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124
    networkURL: https://rpc-amoy.polygon.technology
    defaultGasLimit: 600000
    confirmationTimeout: 10s
    confirmationBlockCount: 5
    receiptTimeout: 600s
    minGasPrice: 0
    maxGasPrice: 1000000
    rpcResponseTimeout: 5s
    waitReceiptCycleTime: 30s
    waitBlockCycleTime: 30s
    gasLess: false
    rhsSettings:
      mode: None
      contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
      rhsUrl: https://rhs-staging.polygonid.me
      chainID: 80002
      publishingKey: pbkey
#
#  zkevm:
#    contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
#    networkURL: <your-rpc-url>
#    defaultGasLimit: 600000
#    confirmationTimeout: 10s
#    confirmationBlockCount: 5
#    receiptTimeout: 600s
#    minGasPrice: 0
#    maxGasPrice: 1000000
#    rpcResponseTimeout: 5s
#    waitReceiptCycleTime: 30s
#    waitBlockCycleTime: 30s
#    gasLess: false
#    rhsSettings:
#      mode: None
#      contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
#      rhsUrl: https://rhs-staging.polygonid.me
#      chainID: 1101
#      publishingKey: pbke
#
#  cardona:
#    contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
#    networkURL: <your-rpc-url>
#    defaultGasLimit: 600000
#    confirmationTimeout: 10s
#    confirmationBlockCount: 5
#    receiptTimeout: 600s
#    minGasPrice: 0
#    maxGasPrice: 1000000
#    rpcResponseTimeout: 5s
#    waitReceiptCycleTime: 30s
#    waitBlockCycleTime: 30s
#    gasLess: false
#    rhsSettings:
#      mode: None
#      contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
#      rhsUrl: https://rhs-staging.polygonid.me
#      chainID: 2442
#      publishingKey: pbke

privado:
  main:
    contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
    networkURL: https://rpc-mainnet.privado.id
    defaultGasLimit: 600000
    confirmationTimeout: 10s
    confirmationBlockCount: 5
    receiptTimeout: 600s
    minGasPrice: 0
    maxGasPrice: 1000000
    rpcResponseTimeout: 5s
    waitReceiptCycleTime: 30s
    waitBlockCycleTime: 30s
    gasLess: false
    rhsSettings:
      mode: None
      contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
      rhsUrl: https://rhs-staging.polygonid.me
      chainID: 21000
      publishingKey: pbke

# ethereum:
#   main:
#     contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
#     networkURL: <your-rpc-url>
#     defaultGasLimit: 600000
#     confirmationTimeout: 10s
#     confirmationBlockCount: 5
#     receiptTimeout: 600s
#     minGasPrice: 0
#     maxGasPrice: 1000000
#     rpcResponseTimeout: 5s
#     waitReceiptCycleTime: 30s
#     waitBlockCycleTime: 30s
#     gasLess: false
#     rhsSettings:
#       mode: None
#       contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
#       rhsUrl: https://rhs-staging.polygonid.me
#       chainID: 1
#       publishingKey: pbke

#   sepolia:
#     contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
#     networkURL: <your-rpc-url>
#     defaultGasLimit: 600000
#     confirmationTimeout: 10s
#     confirmationBlockCount: 5
#     receiptTimeout: 600s
#     minGasPrice: 0
#     maxGasPrice: 1000000
#     rpcResponseTimeout: 5s
#     waitReceiptCycleTime: 30s
#     waitBlockCycleTime: 30s
#     gasLess: false
#     rhsSettings:
#       mode: None
#       contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
#       rhsUrl: https://rhs-staging.polygonid.me
#       chainID: 11155111
#       publishingKey: pbke

# linea:
#   main:
#     contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
#     networkURL: <your-rpc-url>
#     defaultGasLimit: 600000
#     confirmationTimeout: 10s
#     confirmationBlockCount: 5
#     receiptTimeout: 600s
#     minGasPrice: 0
#     maxGasPrice: 1000000
#     rpcResponseTimeout: 5s
#     waitReceiptCycleTime: 30s
#     waitBlockCycleTime: 30s
#     gasLess: false
#     rhsSettings:
#       mode: None
#       contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
#       rhsUrl: https://rhs-staging.polygonid.me
#       chainID: 59144
#       publishingKey: pbke

#   sepolia:
#     contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
#     networkURL: <your-rpc-url>
#     defaultGasLimit: 600000
#     confirmationTimeout: 10s
#     confirmationBlockCount: 5
#     receiptTimeout: 600s
#     minGasPrice: 0
#     maxGasPrice: 1000000
#     rpcResponseTimeout: 5s
#     waitReceiptCycleTime: 30s
#     waitBlockCycleTime: 30s
#     gasLess: false
#     rhsSettings:
#       mode: None
#       contractAddress: 0x7dF78ED37d0B39Ffb6d4D527Bb1865Bf85B60f81
#       rhsUrl: https://rhs-staging.polygonid.me
#       chainID: 59141
#       publishingKey: pbke

#  customNetwork:
#    contractAddress: { replace with state contract }
#    networkURL: { replace with custom RPC }
#    chainID: { replace with chain ID }
#    networkFlag: { replace with network flag, e.g 0b0011_0001 }
#    method: iden3
#    defaultGasLimit: 600000
#    confirmationTimeout: 10s
#    confirmationBlockCount: 5
#    receiptTimeout: 600s
#    minGasPrice: 0
#    maxGasPrice: 1000000
#    rpcResponseTimeout: 5s
#    waitReceiptCycleTime: 30s
#    waitBlockCycleTime: 30s
#    gasLess: false
#    rhsSettings:
#      mode: { None | OffChain | OnChain | All}
#      contractAddress: 0xbEeB6bB53504E8C872023451fd0D23BeF01d320B
#      rhsUrl: https://rhs-staging.polygonid.me
#      chainID: 137
#      publishingKey: pbkey