apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-issuer-node
  labels:
    app: ui-issuer-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-issuer-node
  template:
    metadata:
      labels:
        app: ui-issuer-node # Label for the pod and will be used in the service
    spec:
      containers:
        - name: ui
          image: martinsaporiti/issuernode_ui
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: issuer-node-ui-configmap
          
          # livenessProbe:
          #   httpGet:
          #     path: /status
          #     port: 3001
          #     httpHeaders:
          #     - name: Custom-Header
          #       value: Awesome
          #   initialDelaySeconds: 3
          #   periodSeconds: 60
      