apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ui-issuer-node
  labels:
    app: api-ui-issuer-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ui-issuer-node
  template:
    metadata:
      labels:
        app: api-ui-issuer-node # Label for the pod and will be used in the service
    spec:
      initContainers:
        - name: init-vault-check
          image: 0xpolygon/issuernode
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: issuer-node-api-configmap
          env:
            - name: ISSUER_DATABASE_URL
              value: "postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable"
            - name: ISSUER_KEY_STORE_ADDRESS
              value: "http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)"

          command: ["sh", "-c", "while true; do if cat /vault/data/token.txt; then break; fi; sleep 5; done"]

          volumeMounts:
            - mountPath: /vault/data
              name: vault-volume

        - name: did-initializer
          image: 0xpolygon/issuernode
          imagePullPolicy: "Always"
          envFrom:
            - configMapRef:
                name: issuer-node-api-configmap
            - configMapRef:
                name: issuer-node-api-ui-configmap
          env:
            - name: ISSUER_DATABASE_URL
              value: "postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable"

            - name: ISSUER_KEY_STORE_ADDRESS
              value: "http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)" 
            
          command: ["sh", "-c"]
          args: ["./migrate; ./issuer_initializer;"]
          volumeMounts:
          - mountPath: /did/data/
            name: issuer-node-volume
            readOnly: false
          - mountPath: /vault/data
            name: vault-volume

      containers:
        - name: api-ui
          image: martinsaporiti/issuernode_alpine4
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: issuer-node-api-configmap
            - configMapRef:
                name: issuer-node-api-ui-configmap
          env:
            - name: ISSUER_DATABASE_URL
              value: "postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable"

            - name: ISSUER_KEY_STORE_ADDRESS
              value: "http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)" 
            
          command: ["sh", "-c"]
          args: ["./migrate; ./platform_ui"]

          volumeMounts:
          - mountPath: /did/data
            name: issuer-node-volume
          - mountPath: /vault/data
            name: vault-volume

          livenessProbe:
            httpGet:
              path: /status
              port: 3002
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 60
          
      volumes:
      - name: issuer-node-volume
        persistentVolumeClaim:
          claimName: issuer-node-pvc
      - name: vault-volume
        persistentVolumeClaim:
            claimName: vault-issuer-node-pvc
      