apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-issuer-node
  labels:
    app: api-issuer-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-issuer-node
  template:
    metadata:
      labels:
        app: api-issuer-node # Label for the pod and will be used in the service
    spec:
      containers:
        - name: api
          image: x1m3/issuer-node
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: issuer-node-api-configmap
          env:
            - name: ISSUER_DATABASE_URL
              value: "postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable"
            - name: ISSUER_KEY_STORE_ADDRESS
              value: "http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)" 
          
          command: ["sh", "-c"]
          args: ["./migrate; ./platform"]

          volumeMounts: 
          - mountPath: /vault/data
            name: vault-volume

          livenessProbe:
            httpGet:
              path: /status
              port: 3001
              httpHeaders:
              - name: Custom-Header
                value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 60
      
      volumes:
      - name: vault-volume
        persistentVolumeClaim:
            claimName: vault-issuer-node-pvc