apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml $.Values.ingress.annotations | nindent 4 }}
  {{- end }}

spec:
  rules:
  - host: {{ .Values.appdomain }}
    http:
      paths:
        {{- range .Values.ingress.apphost.paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
        {{- end }}

  - host: {{ .Values.uidomain }}
    http:
      paths:
        {{- range .Values.ingress.uihost.paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
          {{- end }}


  - host: {{ .Values.apidomain }}
    http:
      paths:
        {{- range .Values.ingress.apihost.paths }}
        - path: {{ .path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .serviceName }}
              port:
                number: {{ .servicePort }}
          {{- end }}