apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.uiIssuerNode.configMap.issuerApiUiName  }}
  labels:
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
data:
  ISSUER_SERVER_URL: {{ include "helpers.api-server-url" . | nindent 4}}
  ISSUER_UI_BLOCK_EXPLORER_URL: {{ include "helpers.issuer-block-explorer" . | nindent 4}}
  ISSUER_API_UI_ISSUER_NAME: {{ .Values.issuerName }}
  ISSUER_UI_IPFS_GATEWAY_URL: {{ .Values.uiIssuerNode.configMap.issuerUiIpfsGatewayUrl }}
  ISSUER_UI_SCHEMA_EXPLORER_AND_BUILDER_URL: {{ .Values.uiIssuerNode.configMap.issuerUiSchemaExplorerAndBuilderUrl }}
  ISSUER_API_AUTH_USER: {{ .Values.uiIssuerNode.configMap.issuerApiAuthUser }}
  ISSUER_API_AUTH_PASSWORD: {{ .Values.uiIssuerNode.configMap.issuerApiAuthPassword }}
  ISSUER_ISSUER_NAME: {{ .Values.issuerName }}
  ISSUER_UI_INSECURE: {{ .Values.issuerUiInsecure | quote }}
  ISSUER_UI_AUTH_PASSWORD: {{ .Values.uiPassword }}
  ISSUER_UI_AUTH_USERNAME: {{ .Values.uiIssuerNode.configMap.issuerUiAuthUsername }}
  ISSUER_UI_BASE_URL: "/"