apiVersion: v1
kind: ServiceAccount
metadata:
  name:
  namespace: {{ .Values.namespace }}
  labels:
      {{- include "polygon-id-issuer.staticLabel" . | nindent 4}}
      {{- include "polygon-id-issuer.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: pod-reader
  labels:
      {{- include "polygon-id-issuer.staticLabel" . | nindent 4}}
      {{- include "polygon-id-issuer.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: {{ .Values.namespace }}
  labels:
      {{- include "polygon-id-issuer.staticLabel" . | nindent 4}}
      {{- include "polygon-id-issuer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader # name of Role
subjects: # points to the ServiceAccount
  - kind: ServiceAccount
    name: issuer-node-service-account # service account to bind to
    namespace: {{ .Values.namespace }} # ns of service account