apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-issuer-node-pv 
  labels:
    app: issuer-node
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/volume_1"

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: {{ .Values.postgresIssuerNode.pvc.postgres }}
  labels:
  {{- include "polygon-id-issuer.labels" . | nindent 4 }} 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresIssuerNode.pvc.storageRequest }}