apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vaultIssuerNode.service.name }}
  labels: 
    {{ include "polygon-id-issuer.staticLabel" . }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "polygon-id-issuer.vaultIssuerNode.Labels" . | nindent 4 }}
    {{- include "polygon-id-issuer.selectorLabels" . | nindent 4 }}
  {{- with .Values.vaultIssuerNode.service.ports }}
  ports: 
    {{-  toYaml . | nindent 2 }}
  {{- end }}