
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vaultIssuerNode.deployment.name }}
  labels:
    {{- include "polygon-id-issuer.vaultIssuerNode.deploymentLabels" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vaultIssuerNode.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "polygon-id-issuer.vaultIssuerNode.Labels" . | nindent 6 }}
      {{- include "polygon-id-issuer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polygon-id-issuer.vaultIssuerNode.Labels" . | nindent 8 }}
        {{- include "polygon-id-issuer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "helpers.serviceAccountName" . }}
      containers:
        - name: {{ .Values.vaultIssuerNode.deployment.containerName }}
          securityContext: 
            capabilities:
              add:
                - {{ .Values.vaultIssuerNode.deployment.vault.containerSecurityContext.capabilities.add }}
          image: {{ .Values.vaultIssuerNode.deployment.vault.image.repository }}:{{ .Values.vaultIssuerNode.deployment.vault.image.tag }}
          imagePullPolicy: {{ .Values.vaultIssuerNode.deployment.vault.imagePullPolicy | quote }}
          env:
          - name: {{ .Values.vaultIssuerNode.deployment.vault.env.name1 }}
            value: {{ quote .Values.vaultIssuerNode.deployment.vault.env.vaultAddr }}
          - name: {{ .Values.vaultIssuerNode.deployment.vault.env.name2 }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.vaultIssuerNode.deployment.vault.env.secretKeyRef.name }}
                key: {{ .Values.vaultIssuerNode.deployment.vault.env.secretKeyRef.key }}
          ports:
            - containerPort: {{ .Values.vaultIssuerNode.deployment.containerPort }}
          command: {{ .Values.vaultIssuerNode.deployment.command }}
          volumeMounts: {{- toYaml .Values.vaultIssuerNode.deployment.volumeMounts | nindent 10 }} 
      volumes:
      - name: {{ .Values.vaultIssuerNode.pvc.volumeName }}
        persistentVolumeClaim:
            claimName: {{ .Values.vaultIssuerNode.pvc.vault }}
      - name: {{ .Values.vaultIssuerNode.configMap.vaultConfigName }}
        configMap:
          name: {{ .Values.vaultIssuerNode.configMap.vaultConfigName }}
          defaultMode: 0500
          items:
          - key: {{ .Values.vaultIssuerNode.configMap.vaultConfigPath1 }}
            path: {{ .Values.vaultIssuerNode.configMap.vaultConfigPath1 }}
          - key: {{ .Values.vaultIssuerNode.configMap.vaultConfigPath2 }}
            path: {{ .Values.vaultIssuerNode.configMap.vaultConfigPath2 }}
          - key: {{ .Values.vaultIssuerNode.configMap.vaultConfigPath3 }}
            path: {{ .Values.vaultIssuerNode.configMap.vaultConfigPath3 }}