name: Test API

on:
  push:
    branches:
      - develop-v2

jobs:
  run-tests:
    name: Run tests
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build docker image
        run: docker build -t my-playwright-tests -f ./api_tests/Dockerfile  ./api_tests

      - name: build issuer docker image
        run: make build

      - name: Docker Compose Infra
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './infrastructure/local/docker-compose-infra.yml'
          services: |
            postgres
            vault
            test_local_files_apache
            

      - name: copy .env files
        run: |
          cp .env-api.sample .env-api
          cp .env-issuer.sample .env-issuer

      - name: Docker Compose Issuer Node
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './infrastructure/local/docker-compose.yml'
          services: |
            api

      - name: Run tests
        run: docker run --rm --network issuer-network -e ISSUER_API_URL=http://issuer-api-1:3001 -e ISSUER_API_UI_AUTH_USER=user-issuer -e ISSUER_API_UI_AUTH_PASSWORD=password-issuer my-playwright-tests npx playwright test

                  
